export const DATE_FILTER_ENABLED = "DATE_FILTER_ENABLED";
export const DATE_FILTER_DISABLED= "DATE_FILTER_DISABLED";
export const SEASON_FILTER_ENABLED= "SEASON_FILTER_ENABLED";
export const SEASON_FILTER_DISABLED= "SEASON_FILTER_DISABLED";
export const POKERNIGHT_FILTER_ENABLED = "POKERNIGHT_FILTER_ENABLED";
export const POKERNIGHT_FILTER_DISABLED = "POKERNIGHT_FILTER_DISABLED";
